name: mvn verify

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 1.8, 11, 17 ]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Install current version
        run: mvn -B --no-transfer-progress --show-version clean install -DskipTests
      - name: Verify
        run: mvn -B --no-transfer-progress --show-version verify
